spring:
  application:
    name: ProductService

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/productdb
    username: postgres
    password: suvam123
    #username: ${DB_USER}
    #password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
